---
stages:
    - check

# #### BUILD
Building Docker Images:
    image: registry.gitlab.com/toulousain79/mysb_dev/project_validation/project_validation:latest
    stage: check
    when: manual

    script:
        # #### Check scripts
        - |
            for script in $(ls -A1 /builds/${CI_PROJECT_PATH}/ci/scripts/*.bsh); do
                . ${script}
            done
